id = "unilang"
name = "Unilang"
description = "Language support for Unilang programming language"
version = "0.1.0"
schema_version = 1
authors = ["Paul Passeron <paul.passeron2@gmail.com>"]
repository = "https://github.com/Paul-Passeron/unilang-support"
[grammars.unilang]
repository = "https://github.com/Paul-Passeron/tree-sitter-unilang"
commit = "08b431d5295943131ad1bdf9fd3f32707bc5a625"
